language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "10"
install:
  - npm install
script:
  - npm run lint
  - npm run test
branches:
  only:
    - prod
before_deploy:
  npm build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: prodz